[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm.git"

["lib/pyenv"]
type = "git-repo"
url = "https://github.com/pyenv/pyenv.git"

["lib/pyenv/plugins/pyenv-virtualenv"]
type = "git-repo"
url = "https://github.com/pyenv/pyenv-virtualenv.git"
