# Mac恢复用户空间
if-shell 'test "$(uname -s)" = Darwin' 'set-option -g default-command "exec reattach-to-user-namespace -l $SHELL"'
# prefix设置为⌃+a
unbind C-b
set -g prefix C-a
bind C-a send-prefix
# source config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded.."
# 同步pane
bind '=' setw synchronize-panes
# 使用- |分隔pane
unbind '"'
bind - splitw -v -c '#{pane_current_path}'
unbind %
bind '\' splitw -h -c '#{pane_current_path}'
# 开启鼠标支持
set-option -g mouse on
# kjhl切换pane
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
# 调整pane大小
bind -r ^k resizep -U 10
bind -r ^j resizep -D 10
bind -r ^h resizep -L 10
bind -r ^l resizep -R 10
# 设置风格为vi
setw -g mode-keys vi

# set-option -g set-titles on
# set-option -g set-titles-string "#S / #W"
set -g base-index 1 # 设置窗口的起始下标为1
set -g pane-base-index 1 # 设置面板的起始下标为1
set -g status-interval 2 # 状态栏刷新时间
set -g default-terminal "xterm-256color"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'xiao0yy/dracula-tmux'

set -g @continuum-restore 'on'
set -g @dracula-plugins 'ram-usage cpu-usage network-bandwidth'
set -g @dracula-refresh-rate '1'
set -g @dracula-show-powerline true
set -g @dracula-show-left-icon session
set -g @dracula-border-contrast true

run '~/.tmux/plugins/tpm/tpm'
